name: "Auto Update Branch V5"
on:
  workflow_dispatch:
  schedule:
  - cron: "0 6 * * *"
env:
  BRANCH: "v5"
  VERSION: v5
jobs:
  get_versions:
    name: Get Versions
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.read_version.outputs.version }}
      latest_version: ${{ steps.latest_versions.outputs.tag }}
    steps:
    - uses: actions/checkout@v2
      name: Setup Repo
    - name: Setup Upstream Repo
      uses: actions/checkout@v2
      with:
        repository: SudhanPlayz/Discord-MusicBot
        ref: ${{ env.BRANCH }}
        path: upstream
        submodules: true
    - name: Get Current Release
      id: latest_versions
      working-directory: upstream
      run: |
        content="$(git log --pretty=format:'%H' -n 1)"
        echo "::set-output name=tag::$content"
        
    - name: Log latest image Tag
      run: |
        echo "Latest Image Tag - ${{ steps.latest_versions.outputs.tag }}"

    - name: Read Version
      id: read_version
      run: |
        content="$(cat manifest/v5.hash)"
        echo "::set-output name=version::$content"
        
    - name: Log current image Tag
      run: |
        echo "Current Image Tag - ${{ steps.read_version.outputs.version }}"

  update_versions:
    name: Update commit hash file
    runs-on: ubuntu-latest
    needs: get_versions
    outputs:
      version: ${{ steps.version_fetcher.outputs.version }}
    if: needs.get_versions.outputs.latest_version != needs.get_versions.outputs.current_version
    steps:
    - uses: actions/checkout@v2
    - name: Commit version updates to repo
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        echo -e "${{ needs.get_versions.outputs.latest_version }}" > ./manifest/v5.hash
        git add .
        git commit -m "Automatically updated commit hash." || echo "Nothing to commit"
        git push || echo "Nothing to push"
    - name: Get the latest version from the file
      id: version_fetcher
      run: echo "::set-output name=version::$(cat ./manifest/unprocessed_versions.txt | sort -Vr | head -n 1)"
  
  request-image-build:
    needs: update_versions
    uses: ./.github/workflows/build-image.yml
    with:
      version: dev-v5
      ref: "v5"
