name: Build Image

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      ref:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: sudhanplayz-discord-musicbot
jobs:
  build_push_image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
    - name: Setup Repo
      uses: actions/checkout@v2
      
    - name: Log version to build
      run: "echo \"To build version: ${{ inputs.version }}\"" 
      
    - name: Setup Upstream Repo
      uses: actions/checkout@v2
      with:
        repository: SudhanPlayz/Discord-MusicBot
        ref: "${{ inputs.ref }}"
        path: upstream
        submodules: true

    - name: Copy dockerfile
      run: cp ${{ inputs.dockerfile }} upstream/Dockerfile

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Github Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: ./upstream
        file: ./upstream/Dockerfile
        platforms: linux/amd64
        push: true
        build-args: VERSION=${{ inputs.version }}
        tags: |
          "${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest"
          "${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ inputs.version }}"
